import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics book
  bookSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      items: [
        'book/chapter-1-introduction-to-physical-ai',
        'book/chapter-2-fundamentals-of-humanoid-robotics',
        'book/chapter-3-machine-learning-applications',
        'book/chapter-4-hardware-and-software-architectures',
      ],
    },
    {
      type: 'category',
      label: 'Research & References',
      items: [
        'book/research',
        'book/references',
      ],
    },
    {
      type: 'category',
      label: 'Appendices',
      items: [
        'book/style-guide',
        'book/glossary',
      ],
    },
  ],
};

export default sidebars;
